@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredintials: true

{
  "username": "" ,
  "gender": "",
  "dob": "",
  "email": "",
  "mobileNumber": "",
  "password": "",
  "avatarColor": "",
}
